import { closeMongoClient } from '@app/web/external-apis/conseiller-numerique/conseillerNumeriqueMongoClient'
import { importCrasConseillerNumeriqueV1 } from '@app/web/external-apis/conseiller-numerique/importCrasConseillerNumeriqueV1'
import { getRawStatistiquesCrasV1 } from '@app/web/app/coop/(full-width-layout)/archives-v1/computeStatistiquesCrasV1'

// This test was useful for local development but is too slow and fragile for CI
describe.skip('getRawStatistiquesCrasV1', () => {
  // should have only 11 cras on 2 months
  const conseillerNumeriqueId = '607e0ba54f4799986586bcd7'

  beforeAll(async () => {
    await importCrasConseillerNumeriqueV1({
      conseillerNumeriqueId,
    })
  }, 30_000)

  afterAll(async () => {
    await closeMongoClient()
  })

  it('should return empty data for a empty dataset', async () => {
    const data = await getRawStatistiquesCrasV1({ conseillerNumeriqueIds: [] })

    expect(data).toEqual(null)
  }, 30_000)

  it('should return stats for a list of v1 cras', async () => {
    const data = await getRawStatistiquesCrasV1({
      conseillerNumeriqueIds: [conseillerNumeriqueId],
    })

    expect(data).toEqual({
      firstMonth: new Date('2021-08-01T00:00:00.000Z'),
      lastMonth: new Date('2021-09-30T23:59:59.999Z'),
      monthlyStats: [
        {
          accompagnements: 3,
          age_de_12_a_18_ans: 0,
          age_de_18_a_35_ans: 1,
          age_de_35_a_60_ans: 2,
          age_moins_12_ans: 0,
          age_plus_60_ans: 0,
          canal_autre: 0,
          canal_distance: 0,
          canal_domicile: 0,
          canal_rattachement: 3,
          collectifs: 0,
          duree_0_30: 3,
          duree_120_plus: 0,
          duree_30_60: 0,
          duree_60_120: 0,
          individuels: 3,
          month: '2021-09',
          participants_ateliers: 0,
          percentages: {
            age_de_12_a_18_ans: 0,
            age_de_18_a_35_ans: 1 / 3,
            age_de_35_a_60_ans: 2 / 3,
            age_moins_12_ans: 0,
            age_plus_60_ans: 0,
            canal_autre: 0,
            canal_distance: 0,
            canal_domicile: 0,
            canal_rattachement: 1,
            duree_0_30: 1,
            duree_120_plus: 0,
            duree_30_60: 0,
            duree_60_120: 0,
            statut_en_emploi: 2 / 3,
            statut_etudiant: 0,
            statut_heterogene: 0,
            statut_retraite: 0,
            statut_sans_emploi: 1 / 3,
            suivi_atelier: 0,
            suivi_individuel: 1,
            suivi_redirection: 0,
            temps_collectif: 0,
            temps_individuel: 0,
            temps_ponctuel: 0,
            theme_accompagner_enfant: 0,
            theme_autre: 0,
            theme_budget: 0,
            theme_contenus_numeriques: 0,
            theme_courriel: 0,
            theme_demarche_en_ligne: 0,
            theme_diagnostic: 0,
            theme_echanger: 0,
            theme_equipement_informatique: 0.5,
            theme_fraude_et_harcelement: 0,
            theme_internet: 0.25,
            theme_sante: 0,
            theme_scolaire: 0,
            theme_securite: 0,
            theme_smartphone: 0.25,
            theme_tpe_pme: 0,
            theme_traitement_texte: 0,
            theme_trouver_emploi: 0,
            theme_vocabulaire: 0,
          },
          personnes_accompagnees: 3,
          ponctuels: 0,
          statut_en_emploi: 2,
          statut_etudiant: 0,
          statut_heterogene: 0,
          statut_retraite: 0,
          statut_sans_emploi: 1,
          suivi_atelier: 0,
          suivi_individuel: 3,
          suivi_redirection: 0,
          temps_collectif: 0,
          temps_individuel: 0,
          temps_ponctuel: 0,
          temps_total: 0,
          theme_accompagner_enfant: 0,
          theme_autre: 0,
          theme_budget: 0,
          theme_contenus_numeriques: 0,
          theme_courriel: 0,
          theme_demarche_en_ligne: 0,
          theme_diagnostic: 0,
          theme_echanger: 0,
          theme_equipement_informatique: 2,
          theme_fraude_et_harcelement: 0,
          theme_internet: 1,
          theme_sante: 0,
          theme_scolaire: 0,
          theme_securite: 0,
          theme_smartphone: 1,
          theme_tpe_pme: 0,
          theme_traitement_texte: 0,
          theme_trouver_emploi: 0,
          theme_vocabulaire: 0,
          total: 3,
        },
        {
          accompagnements: 8,
          age_de_12_a_18_ans: 0,
          age_de_18_a_35_ans: 3,
          age_de_35_a_60_ans: 5,
          age_moins_12_ans: 0,
          age_plus_60_ans: 0,
          canal_autre: 0,
          canal_distance: 0,
          canal_domicile: 0,
          canal_rattachement: 8,
          collectifs: 0,
          duree_0_30: 8,
          duree_120_plus: 0,
          duree_30_60: 0,
          duree_60_120: 0,
          individuels: 8,
          month: '2021-08',
          participants_ateliers: 0,
          percentages: {
            age_de_12_a_18_ans: 0,
            age_de_18_a_35_ans: 0.375,
            age_de_35_a_60_ans: 0.625,
            age_moins_12_ans: 0,
            age_plus_60_ans: 0,
            canal_autre: 0,
            canal_distance: 0,
            canal_domicile: 0,
            canal_rattachement: 1,
            duree_0_30: 1,
            duree_120_plus: 0,
            duree_30_60: 0,
            duree_60_120: 0,
            statut_en_emploi: 0.5,
            statut_etudiant: 0,
            statut_heterogene: 0,
            statut_retraite: 0.125,
            statut_sans_emploi: 0.375,
            suivi_atelier: 0,
            suivi_individuel: 0.875,
            suivi_redirection: 0.125,
            temps_collectif: 0,
            temps_individuel: 1,
            temps_ponctuel: 0,
            theme_accompagner_enfant: 0,
            theme_autre: 0.125,
            theme_budget: 0,
            theme_contenus_numeriques: 0,
            theme_courriel: 0,
            theme_demarche_en_ligne: 0,
            theme_diagnostic: 0,
            theme_echanger: 0,
            theme_equipement_informatique: 0.5,
            theme_fraude_et_harcelement: 0,
            theme_internet: 0,
            theme_sante: 0,
            theme_scolaire: 0,
            theme_securite: 0,
            theme_smartphone: 0.375,
            theme_tpe_pme: 0,
            theme_traitement_texte: 0,
            theme_trouver_emploi: 0,
            theme_vocabulaire: 0,
          },
          personnes_accompagnees: 8,
          ponctuels: 0,
          statut_en_emploi: 4,
          statut_etudiant: 0,
          statut_heterogene: 0,
          statut_retraite: 1,
          statut_sans_emploi: 3,
          suivi_atelier: 0,
          suivi_individuel: 7,
          suivi_redirection: 1,
          temps_collectif: 0,
          temps_individuel: 2,
          temps_ponctuel: 0,
          temps_total: 2,
          theme_accompagner_enfant: 0,
          theme_autre: 1,
          theme_budget: 0,
          theme_contenus_numeriques: 0,
          theme_courriel: 0,
          theme_demarche_en_ligne: 0,
          theme_diagnostic: 0,
          theme_echanger: 0,
          theme_equipement_informatique: 4,
          theme_fraude_et_harcelement: 0,
          theme_internet: 0,
          theme_sante: 0,
          theme_scolaire: 0,
          theme_securite: 0,
          theme_smartphone: 3,
          theme_tpe_pme: 0,
          theme_traitement_texte: 0,
          theme_trouver_emploi: 0,
          theme_vocabulaire: 0,
          total: 8,
        },
      ],
      totalStats: {
        total: 11,
        accompagnements: 11,
        age_de_12_a_18_ans: 0,
        age_de_18_a_35_ans: 4,
        age_de_35_a_60_ans: 7,
        age_moins_12_ans: 0,
        age_plus_60_ans: 0,
        canal_autre: 0,
        canal_distance: 0,
        canal_domicile: 0,
        canal_rattachement: 11,
        collectifs: 0,
        duree_0_30: 11,
        duree_120_plus: 0,
        duree_30_60: 0,
        duree_60_120: 0,
        individuels: 11,
        month: 'total',
        participants_ateliers: 0,
        personnes_accompagnees: 11,
        ponctuels: 0,
        statut_en_emploi: 6,
        statut_etudiant: 0,
        statut_heterogene: 0,
        statut_retraite: 1,
        statut_sans_emploi: 4,
        suivi_atelier: 0,
        suivi_individuel: 10,
        suivi_redirection: 1,
        temps_collectif: 0,
        temps_individuel: 2,
        temps_ponctuel: 0,
        temps_total: 2,
        theme_accompagner_enfant: 0,
        theme_autre: 1,
        theme_budget: 0,
        theme_contenus_numeriques: 0,
        theme_courriel: 0,
        theme_demarche_en_ligne: 0,
        theme_diagnostic: 0,
        theme_echanger: 0,
        theme_equipement_informatique: 6,
        theme_fraude_et_harcelement: 0,
        theme_internet: 1,
        theme_sante: 0,
        theme_scolaire: 0,
        theme_securite: 0,
        theme_smartphone: 4,
        theme_tpe_pme: 0,
        theme_traitement_texte: 0,
        theme_trouver_emploi: 0,
        theme_vocabulaire: 0,

        percentages: {
          age_de_12_a_18_ans: 0,
          age_de_18_a_35_ans: 0.363_636_363_636_363_65,
          age_de_35_a_60_ans: 0.636_363_636_363_636_4,
          age_moins_12_ans: 0,
          age_plus_60_ans: 0,
          canal_autre: 0,
          canal_distance: 0,
          canal_domicile: 0,
          canal_rattachement: 1,
          duree_0_30: 1,
          duree_120_plus: 0,
          duree_30_60: 0,
          duree_60_120: 0,
          statut_en_emploi: 0.545_454_545_454_545_4,
          statut_etudiant: 0,
          statut_heterogene: 0,
          statut_retraite: 0.090_909_090_909_090_91,
          statut_sans_emploi: 0.363_636_363_636_363_65,
          suivi_atelier: 0,
          suivi_individuel: 0.909_090_909_090_909_1,
          suivi_redirection: 0.090_909_090_909_090_91,
          temps_collectif: 0,
          temps_individuel: 1,
          temps_ponctuel: 0,
          theme_accompagner_enfant: 0,
          theme_autre: 0.083_333_333_333_333_33,
          theme_budget: 0,
          theme_contenus_numeriques: 0,
          theme_courriel: 0,
          theme_demarche_en_ligne: 0,
          theme_diagnostic: 0,
          theme_echanger: 0,
          theme_equipement_informatique: 0.5,
          theme_fraude_et_harcelement: 0,
          theme_internet: 0.083_333_333_333_333_33,
          theme_sante: 0,
          theme_scolaire: 0,
          theme_securite: 0,
          theme_smartphone: 1 / 3,
          theme_tpe_pme: 0,
          theme_traitement_texte: 0,
          theme_trouver_emploi: 0,
          theme_vocabulaire: 0,
        },
      },
    })
  }, 30_000)
})
