type FieldInfo = {
  count: number
  nullCount: number
  notNullCount: number
  type?: string
}

type CollectionInfo = {
  count: number
  fields: Record<string, FieldInfo>
}
export const conseillerNumeriqueMongoCollections: Record<
  string,
  CollectionInfo
> = {
  accessLogs: {
    count: 625_677,
    fields: {
      _id: {
        count: 625_678,
        nullCount: 0,
        notNullCount: 625_678,
        type: 'object',
      },
      name: {
        count: 625_004,
        nullCount: 9,
        notNullCount: 624_995,
        type: 'string',
      },
      createdAt: {
        count: 625_678,
        nullCount: 0,
        notNullCount: 625_678,
        type: 'object',
      },
      ip: {
        count: 625_678,
        nullCount: 0,
        notNullCount: 625_678,
        type: 'string',
      },
      connexionError: {
        count: 102_433,
        nullCount: 0,
        notNullCount: 102_433,
        type: 'boolean',
      },
    },
  },
  structures: {
    count: 6556,
    fields: {
      _id: { count: 6556, nullCount: 0, notNullCount: 6556, type: 'object' },
      idPG: { count: 6556, nullCount: 0, notNullCount: 6556, type: 'object' },
      type: { count: 6556, nullCount: 0, notNullCount: 6556, type: 'string' },
      statut: { count: 6556, nullCount: 0, notNullCount: 6556, type: 'string' },
      nom: { count: 6556, nullCount: 0, notNullCount: 6556, type: 'string' },
      siret: {
        count: 6556,
        nullCount: 148,
        notNullCount: 6408,
        type: 'string',
      },
      aIdentifieCandidat: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'boolean',
      },
      dateDebutMission: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'object',
      },
      nombreConseillersSouhaites: {
        count: 6556,
        nullCount: 1020,
        notNullCount: 5536,
        type: 'object',
      },
      estLabelliseFranceServices: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'string',
      },
      codePostal: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'string',
      },
      location: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'object',
      },
      nomCommune: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'string',
      },
      codeCommune: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'string',
      },
      codeDepartement: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'string',
      },
      codeRegion: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'string',
      },
      emailConfirmedAt: {
        count: 6556,
        nullCount: 1023,
        notNullCount: 5533,
        type: 'object',
      },
      emailConfirmationKey: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'string',
      },
      unsubscribedAt: {
        count: 6556,
        nullCount: 6554,
        notNullCount: 2,
        type: 'object',
      },
      unsubscribeExtras: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'object',
      },
      createdAt: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'object',
      },
      updatedAt: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'object',
      },
      validatedAt: {
        count: 6556,
        nullCount: 6552,
        notNullCount: 4,
        type: 'object',
      },
      importedAt: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'object',
      },
      deleted_at: { count: 6556, nullCount: 6556, notNullCount: 0 },
      userCreated: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'boolean',
      },
      coordonneesInsee: {
        count: 6085,
        nullCount: 0,
        notNullCount: 6085,
        type: 'object',
      },
      coselec: {
        count: 6385,
        nullCount: 0,
        notNullCount: 6385,
        type: 'object',
      },
      estZRR: {
        count: 6526,
        nullCount: 229,
        notNullCount: 6297,
        type: 'boolean',
      },
      prefet: { count: 6487, nullCount: 0, notNullCount: 6487, type: 'object' },
      contact: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'object',
      },
      qpvListe: {
        count: 5927,
        nullCount: 0,
        notNullCount: 5927,
        type: 'object',
      },
      qpvStatut: {
        count: 5927,
        nullCount: 0,
        notNullCount: 5927,
        type: 'string',
      },
      coselecAt: {
        count: 4228,
        nullCount: 0,
        notNullCount: 4228,
        type: 'object',
      },
      codeCom: {
        count: 6556,
        nullCount: 6550,
        notNullCount: 6,
        type: 'string',
      },
      conventionnement: {
        count: 2936,
        nullCount: 0,
        notNullCount: 2936,
        type: 'object',
      },
      insee: { count: 6100, nullCount: 1, notNullCount: 6099, type: 'object' },
      adresseInsee2Ban: {
        count: 6019,
        nullCount: 0,
        notNullCount: 6019,
        type: 'object',
      },
      coordinateurCandidature: {
        count: 6556,
        nullCount: 0,
        notNullCount: 6556,
        type: 'boolean',
      },
      coordinateurTypeContrat: {
        count: 6556,
        nullCount: 6412,
        notNullCount: 144,
        type: 'string',
      },
      demandesCoselec: {
        count: 237,
        nullCount: 0,
        notNullCount: 237,
        type: 'object',
      },
      estLabelliseAidantsConnect: {
        count: 1853,
        nullCount: 0,
        notNullCount: 1853,
        type: 'string',
      },
      reseau: { count: 560, nullCount: 0, notNullCount: 560, type: 'string' },
      historique: {
        count: 626,
        nullCount: 0,
        notNullCount: 626,
        type: 'object',
      },
      demandesCoordinateur: {
        count: 184,
        nullCount: 0,
        notNullCount: 184,
        type: 'object',
      },
      urlPriseRdv: {
        count: 180,
        nullCount: 0,
        notNullCount: 180,
        type: 'string',
      },
      userCreationError: {
        count: 57,
        nullCount: 0,
        notNullCount: 57,
        type: 'boolean',
      },
    },
  },
  permanences_temp: {
    count: 8353,
    fields: {
      _id: { count: 8353, nullCount: 0, notNullCount: 8353, type: 'object' },
      estStructure: {
        count: 8353,
        nullCount: 0,
        notNullCount: 8353,
        type: 'boolean',
      },
      nomEnseigne: {
        count: 8353,
        nullCount: 0,
        notNullCount: 8353,
        type: 'string',
      },
      numeroTelephone: {
        count: 8353,
        nullCount: 4039,
        notNullCount: 4314,
        type: 'string',
      },
      email: {
        count: 8353,
        nullCount: 5154,
        notNullCount: 3199,
        type: 'string',
      },
      siteWeb: {
        count: 8353,
        nullCount: 5104,
        notNullCount: 3249,
        type: 'string',
      },
      siret: {
        count: 8353,
        nullCount: 3919,
        notNullCount: 4434,
        type: 'string',
      },
      adresse: {
        count: 8353,
        nullCount: 0,
        notNullCount: 8353,
        type: 'object',
      },
      location: {
        count: 8353,
        nullCount: 22,
        notNullCount: 8331,
        type: 'object',
      },
      horaires: {
        count: 8353,
        nullCount: 0,
        notNullCount: 8353,
        type: 'object',
      },
      typeAcces: {
        count: 8353,
        nullCount: 0,
        notNullCount: 8353,
        type: 'object',
      },
      conseillers: {
        count: 8353,
        nullCount: 0,
        notNullCount: 8353,
        type: 'object',
      },
      lieuPrincipalPour: {
        count: 8353,
        nullCount: 0,
        notNullCount: 8353,
        type: 'object',
      },
      conseillersItinerants: {
        count: 8353,
        nullCount: 0,
        notNullCount: 8353,
        type: 'object',
      },
      structure: {
        count: 8353,
        nullCount: 0,
        notNullCount: 8353,
        type: 'object',
      },
      updatedAt: {
        count: 8353,
        nullCount: 0,
        notNullCount: 8353,
        type: 'object',
      },
      updatedBy: {
        count: 8353,
        nullCount: 0,
        notNullCount: 8353,
        type: 'object',
      },
    },
  },
  communes: {
    count: 35_357,
    fields: {
      _id: {
        count: 35_357,
        nullCount: 0,
        notNullCount: 35_357,
        type: 'object',
      },
      type: {
        count: 35_357,
        nullCount: 0,
        notNullCount: 35_357,
        type: 'string',
      },
      geometry: {
        count: 35_357,
        nullCount: 0,
        notNullCount: 35_357,
        type: 'object',
      },
      properties: {
        count: 35_357,
        nullCount: 0,
        notNullCount: 35_357,
        type: 'object',
      },
    },
  },
  stats_conseillers_cras_historique: {
    count: 3968,
    fields: {
      '2000': { count: 1, nullCount: 0, notNullCount: 1, type: 'object' },
      '2020': { count: 4, nullCount: 0, notNullCount: 4, type: 'object' },
      '2021': { count: 1475, nullCount: 0, notNullCount: 1475, type: 'object' },
      '2022': { count: 3622, nullCount: 0, notNullCount: 3622, type: 'object' },
      '2023': { count: 3340, nullCount: 0, notNullCount: 3340, type: 'object' },
      _id: { count: 3968, nullCount: 0, notNullCount: 3968, type: 'object' },
      conseiller: {
        count: 3968,
        nullCount: 0,
        notNullCount: 3968,
        type: 'object',
      },
    },
  },
  hubs: {
    count: 17,
    fields: {
      _id: { count: 17, nullCount: 0, notNullCount: 17, type: 'object' },
      name: { count: 17, nullCount: 0, notNullCount: 17, type: 'string' },
      region_names: {
        count: 13,
        nullCount: 0,
        notNullCount: 13,
        type: 'object',
      },
      channelId: { count: 17, nullCount: 0, notNullCount: 17, type: 'string' },
      departements: { count: 4, nullCount: 0, notNullCount: 4, type: 'object' },
    },
  },
  sondages: {
    count: 6649,
    fields: {
      _id: { count: 6649, nullCount: 0, notNullCount: 6649, type: 'object' },
      sondage: {
        count: 6649,
        nullCount: 0,
        notNullCount: 6649,
        type: 'object',
      },
      createdAt: {
        count: 6649,
        nullCount: 0,
        notNullCount: 6649,
        type: 'object',
      },
      conseiller: {
        count: 6649,
        nullCount: 0,
        notNullCount: 6649,
        type: 'object',
      },
    },
  },
  cras: {
    count: 2_214_524,
    fields: {
      _id: {
        count: 2_214_557,
        nullCount: 0,
        notNullCount: 2_214_557,
        type: 'object',
      },
      cra: {
        count: 2_214_557,
        nullCount: 0,
        notNullCount: 2_214_557,
        type: 'object',
      },
      conseiller: {
        count: 2_214_557,
        nullCount: 0,
        notNullCount: 2_214_557,
        type: 'object',
      },
      createdAt: {
        count: 2_214_557,
        nullCount: 0,
        notNullCount: 2_214_557,
        type: 'object',
      },
      structure: {
        count: 2_214_557,
        nullCount: 0,
        notNullCount: 2_214_557,
        type: 'object',
      },
      permanence: {
        count: 1_197_210,
        nullCount: 17_883,
        notNullCount: 1_179_327,
        type: 'object',
      },
      updatedAt: {
        count: 89_589,
        nullCount: 0,
        notNullCount: 89_589,
        type: 'object',
      },
      fixUpdatedAt: {
        count: 53_022,
        nullCount: 0,
        notNullCount: 53_022,
        type: 'object',
      },
    },
  },
  ressourcesTags: {
    count: 0,
    fields: {},
  },
  users: {
    count: 70_440,
    fields: {
      _id: {
        count: 70_440,
        nullCount: 0,
        notNullCount: 70_440,
        type: 'object',
      },
      name: {
        count: 70_440,
        nullCount: 0,
        notNullCount: 70_440,
        type: 'string',
      },
      password: {
        count: 70_254,
        nullCount: 5,
        notNullCount: 70_249,
        type: 'string',
      },
      roles: {
        count: 70_440,
        nullCount: 0,
        notNullCount: 70_440,
        type: 'object',
      },
      entity: {
        count: 70_029,
        nullCount: 0,
        notNullCount: 70_029,
        type: 'object',
      },

      token: {
        count: 70_440,
        nullCount: 69_689,
        notNullCount: 751,
        type: 'string',
      },
      mailSentDate: {
        count: 70_439,
        nullCount: 1,
        notNullCount: 70_438,
        type: 'object',
      },
      passwordCreated: {
        count: 70_440,
        nullCount: 0,
        notNullCount: 70_440,
        type: 'boolean',
      },
      createdAt: {
        count: 70_440,
        nullCount: 0,
        notNullCount: 70_440,
        type: 'object',
      },
      resend: {
        count: 70_439,
        nullCount: 0,
        notNullCount: 70_439,
        type: 'boolean',
      },
      mailCoopSent: {
        count: 3303,
        nullCount: 0,
        notNullCount: 3303,
        type: 'boolean',
      },
      tokenCreatedAt: {
        count: 70_440,
        nullCount: 69_872,
        notNullCount: 568,
        type: 'object',
      },
      passwordCreatedAt: {
        count: 34_316,
        nullCount: 0,
        notNullCount: 34_316,
        type: 'object',
      },
      lastLogin: {
        count: 16_338,
        nullCount: 0,
        notNullCount: 16_338,
        type: 'object',
      },
      mailSentCoselecDate: {
        count: 4471,
        nullCount: 0,
        notNullCount: 4471,
        type: 'object',
      },
      migrationDashboard: {
        count: 5036,
        nullCount: 0,
        notNullCount: 5036,
        type: 'boolean',
      },
      updatedAt: {
        count: 7085,
        nullCount: 0,
        notNullCount: 7085,
        type: 'object',
      },
      sub: { count: 2917, nullCount: 0, notNullCount: 2917, type: 'string' },
      refreshToken: {
        count: 2917,
        nullCount: 0,
        notNullCount: 2917,
        type: 'string',
      },
      attemptFail: {
        count: 411,
        nullCount: 0,
        notNullCount: 411,
        type: 'object',
      },
      lastAttemptFailDate: {
        count: 411,
        nullCount: 0,
        notNullCount: 411,
        type: 'object',
      },
      departement: {
        count: 262,
        nullCount: 0,
        notNullCount: 262,
        type: 'string',
      },
      region: { count: 26, nullCount: 0, notNullCount: 26, type: 'string' },
      mailSendDate: { count: 250, nullCount: 250, notNullCount: 0 },
      nom: {
        count: 65_621,
        nullCount: 0,
        notNullCount: 65_621,
        type: 'string',
      },
      prenom: {
        count: 65_621,
        nullCount: 0,
        notNullCount: 65_621,
        type: 'string',
      },
      reseau: { count: 64, nullCount: 0, notNullCount: 64, type: 'string' },
      mailAModifier: {
        count: 79,
        nullCount: 0,
        notNullCount: 79,
        type: 'string',
      },
      reportPermanence: {
        count: 3100,
        nullCount: 0,
        notNullCount: 3100,
        type: 'object',
      },
      resetPasswordCnil: {
        count: 23_696,
        nullCount: 0,
        notNullCount: 23_696,
        type: 'boolean',
      },
      mailSendSupportchangeEmailCnfsDate: {
        count: 24,
        nullCount: 0,
        notNullCount: 24,
        type: 'object',
      },
      resendSupportchangeEmailCnfs: {
        count: 24,
        nullCount: 0,
        notNullCount: 24,
        type: 'boolean',
      },
      support_cnfs: { count: 8, nullCount: 0, notNullCount: 8, type: 'object' },
      mailCoordinateurSent: {
        count: 62,
        nullCount: 0,
        notNullCount: 62,
        type: 'boolean',
      },
      mailConfirmError: {
        count: 14,
        nullCount: 0,
        notNullCount: 14,
        type: 'string',
      },
      mailConfirmErrorDetail: {
        count: 14,
        nullCount: 0,
        notNullCount: 14,
        type: 'string',
      },
      mailSendConfirmechangeEmailCnfsDate: {
        count: 15,
        nullCount: 0,
        notNullCount: 15,
        type: 'object',
      },
      resendConfirmechangeEmailCnfs: {
        count: 15,
        nullCount: 0,
        notNullCount: 15,
        type: 'boolean',
      },
      numberLoginUnblock: {
        count: 4,
        nullCount: 0,
        notNullCount: 4,
        type: 'object',
      },
      hub: { count: 24, nullCount: 0, notNullCount: 24, type: 'string' },
      mailSentCoselecCoordinateurDate: {
        count: 25,
        nullCount: 0,
        notNullCount: 25,
        type: 'object',
      },
      mailError: { count: 1, nullCount: 0, notNullCount: 1, type: 'string' },
      mailErrorDetail: {
        count: 1,
        nullCount: 0,
        notNullCount: 1,
        type: 'string',
      },
    },
  },
  ressources: {
    count: 0,
    fields: {},
  },
  qpv: {
    count: 1514,
    fields: {
      _id: { count: 1514, nullCount: 0, notNullCount: 1514, type: 'object' },
      type: { count: 1514, nullCount: 0, notNullCount: 1514, type: 'string' },
      properties: {
        count: 1514,
        nullCount: 0,
        notNullCount: 1514,
        type: 'object',
      },
      geometry: {
        count: 1514,
        nullCount: 0,
        notNullCount: 1514,
        type: 'object',
      },
    },
  },
  stats_conseillers_cras: {
    count: 4419,
    fields: {
      '2000': { count: 1, nullCount: 0, notNullCount: 1, type: 'object' },
      '2020': { count: 4, nullCount: 0, notNullCount: 4, type: 'object' },
      '2021': { count: 1465, nullCount: 0, notNullCount: 1465, type: 'object' },
      '2022': { count: 3631, nullCount: 0, notNullCount: 3631, type: 'object' },
      '2023': { count: 3656, nullCount: 0, notNullCount: 3656, type: 'object' },
      '2024': { count: 2569, nullCount: 0, notNullCount: 2569, type: 'object' },
      _id: { count: 4419, nullCount: 0, notNullCount: 4419, type: 'object' },
      conseiller: {
        count: 4419,
        nullCount: 0,
        notNullCount: 4419,
        type: 'object',
      },
    },
  },
  conseillers: {
    count: 71_866,
    fields: {
      _id: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'object',
      },
      idPG: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'object',
      },
      prenom: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'string',
      },
      nom: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'string',
      },
      email: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'string',
      },
      telephone: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'string',
      },
      distanceMax: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'object',
      },
      disponible: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'boolean',
      },
      dateDisponibilite: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'object',
      },
      estDemandeurEmploi: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'boolean',
      },
      estEnEmploi: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'boolean',
      },
      estEnFormation: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'boolean',
      },
      estDiplomeMedNum: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'boolean',
      },
      nomDiplomeMedNum: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'string',
      },
      aUneExperienceMedNum: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'boolean',
      },
      codePostal: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'string',
      },
      location: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'object',
      },
      nomCommune: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'string',
      },
      codeCommune: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'string',
      },
      codeDepartement: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'string',
      },
      codeRegion: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'string',
      },
      emailConfirmedAt: {
        count: 71_866,
        nullCount: 16_273,
        notNullCount: 55_593,
        type: 'object',
      },
      emailConfirmationKey: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'string',
      },
      unsubscribedAt: {
        count: 71_866,
        nullCount: 71_749,
        notNullCount: 117,
        type: 'object',
      },
      unsubscribeExtras: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'object',
      },
      createdAt: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'object',
      },
      updatedAt: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'object',
      },
      importedAt: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'object',
      },
      deletedAt: {
        count: 71_866,
        nullCount: 71_865,
        notNullCount: 1,
        type: 'object',
      },
      userCreated: {
        count: 71_866,
        nullCount: 0,
        notNullCount: 71_866,
        type: 'boolean',
      },
      pix: {
        count: 32_093,
        nullCount: 0,
        notNullCount: 32_093,
        type: 'object',
      },
      sondageSentAt: {
        count: 23_003,
        nullCount: 0,
        notNullCount: 23_003,
        type: 'object',
      },
      codeCom: {
        count: 71_866,
        nullCount: 71_841,
        notNullCount: 25,
        type: 'string',
      },
      sondageToken: {
        count: 22_079,
        nullCount: 0,
        notNullCount: 22_079,
        type: 'string',
      },
      dateFinFormation: {
        count: 4979,
        nullCount: 741,
        notNullCount: 4238,
        type: 'object',
      },
      datePrisePoste: {
        count: 4979,
        nullCount: 760,
        notNullCount: 4219,
        type: 'object',
      },
      estRecrute: {
        count: 3331,
        nullCount: 0,
        notNullCount: 3331,
        type: 'boolean',
      },
      statut: { count: 5035, nullCount: 0, notNullCount: 5035, type: 'string' },
      structureId: {
        count: 3331,
        nullCount: 0,
        notNullCount: 3331,
        type: 'object',
      },
      mattermost: {
        count: 4783,
        nullCount: 0,
        notNullCount: 4783,
        type: 'object',
      },
      emailCN: {
        count: 4961,
        nullCount: 0,
        notNullCount: 4961,
        type: 'object',
      },
      emailCNError: {
        count: 3326,
        nullCount: 0,
        notNullCount: 3326,
        type: 'boolean',
      },
      dateDeNaissance: {
        count: 31_199,
        nullCount: 0,
        notNullCount: 31_199,
        type: 'object',
      },
      sexe: {
        count: 31_199,
        nullCount: 0,
        notNullCount: 31_199,
        type: 'string',
      },
      groupeCRA: {
        count: 4124,
        nullCount: 0,
        notNullCount: 4124,
        type: 'object',
      },
      groupeCRAHistorique: {
        count: 4096,
        nullCount: 0,
        notNullCount: 4096,
        type: 'object',
      },
      telephonePro: {
        count: 3138,
        nullCount: 991,
        notNullCount: 2147,
        type: 'string',
      },
      emailPro: {
        count: 3206,
        nullCount: 208,
        notNullCount: 2998,
        type: 'string',
      },
      supHierarchique: {
        count: 2713,
        nullCount: 0,
        notNullCount: 2713,
        type: 'object',
      },
      hasPermanence: {
        count: 2998,
        nullCount: 0,
        notNullCount: 2998,
        type: 'boolean',
      },
      codeRegionStructure: {
        count: 3331,
        nullCount: 0,
        notNullCount: 3331,
        type: 'string',
      },
      codeDepartementStructure: {
        count: 3331,
        nullCount: 0,
        notNullCount: 3331,
        type: 'string',
      },
      certifie: {
        count: 2994,
        nullCount: 0,
        notNullCount: 2994,
        type: 'boolean',
      },
      mailActiviteCRAMois: {
        count: 390,
        nullCount: 0,
        notNullCount: 390,
        type: 'string',
      },
      certificationPixFormation: {
        count: 2281,
        nullCount: 0,
        notNullCount: 2281,
        type: 'boolean',
      },
      resetPasswordCNError: {
        count: 3258,
        nullCount: 0,
        notNullCount: 3258,
        type: 'boolean',
      },
      coordinateurs: {
        count: 1676,
        nullCount: 0,
        notNullCount: 1676,
        type: 'object',
      },
      ruptures: {
        count: 1860,
        nullCount: 0,
        notNullCount: 1860,
        type: 'object',
      },
      cv: { count: 3060, nullCount: 0, notNullCount: 3060, type: 'object' },
      estCoordinateur: {
        count: 66,
        nullCount: 0,
        notNullCount: 66,
        type: 'boolean',
      },
      listeSubordonnes: {
        count: 61,
        nullCount: 0,
        notNullCount: 61,
        type: 'object',
      },
      userCreationError: {
        count: 6199,
        nullCount: 0,
        notNullCount: 6199,
        type: 'boolean',
      },
      mailProAModifier: {
        count: 53,
        nullCount: 0,
        notNullCount: 53,
        type: 'string',
      },
      tokenChangementMailPro: {
        count: 53,
        nullCount: 0,
        notNullCount: 53,
        type: 'string',
      },
      tokenChangementMailProCreatedAt: {
        count: 53,
        nullCount: 0,
        notNullCount: 53,
        type: 'object',
      },
      mailConfirmError: {
        count: 3,
        nullCount: 0,
        notNullCount: 3,
        type: 'string',
      },
      mailConfirmErrorDetail: {
        count: 3,
        nullCount: 0,
        notNullCount: 3,
        type: 'string',
      },
      historique: { count: 16, nullCount: 0, notNullCount: 16, type: 'object' },
      mailAModifier: {
        count: 15,
        nullCount: 0,
        notNullCount: 15,
        type: 'string',
      },
      tokenChangementMail: {
        count: 15,
        nullCount: 0,
        notNullCount: 15,
        type: 'string',
      },
      tokenChangementMailCreatedAt: {
        count: 15,
        nullCount: 0,
        notNullCount: 15,
        type: 'object',
      },
      nonAffichageCarto: {
        count: 8,
        nullCount: 0,
        notNullCount: 8,
        type: 'boolean',
      },
      ruptureError: {
        count: 1,
        nullCount: 0,
        notNullCount: 1,
        type: 'boolean',
      },
    },
  },
  conseillersTermines: {
    count: 0,
    fields: {},
  },
  cras_deleted: {
    count: 5911,
    fields: {
      _id: { count: 5911, nullCount: 0, notNullCount: 5911, type: 'object' },
      deletedAt: {
        count: 5911,
        nullCount: 0,
        notNullCount: 5911,
        type: 'object',
      },
      conseillerId: {
        count: 2290,
        nullCount: 0,
        notNullCount: 2290,
        type: 'object',
      },
      craObj: { count: 2290, nullCount: 0, notNullCount: 2290, type: 'object' },
    },
  },
  conseillersSupprimes: {
    count: 1061,
    fields: {
      _id: { count: 1061, nullCount: 0, notNullCount: 1061, type: 'object' },
      deletedAt: {
        count: 1061,
        nullCount: 0,
        notNullCount: 1061,
        type: 'object',
      },
      motif: { count: 1061, nullCount: 39, notNullCount: 1022, type: 'string' },
      conseiller: {
        count: 1061,
        nullCount: 0,
        notNullCount: 1061,
        type: 'object',
      },
      actionUser: {
        count: 1052,
        nullCount: 39,
        notNullCount: 1013,
        type: 'string',
      },
      role: { count: 9, nullCount: 0, notNullCount: 9, type: 'string' },
      userId: { count: 9, nullCount: 0, notNullCount: 9, type: 'string' },
      __v: { count: 9, nullCount: 0, notNullCount: 9, type: 'object' },
      historiqueContrats: {
        count: 102,
        nullCount: 0,
        notNullCount: 102,
        type: 'object',
      },
    },
  },
  conseillersRuptures: {
    count: 1912,
    fields: {
      _id: { count: 1912, nullCount: 0, notNullCount: 1912, type: 'object' },
      conseillerId: {
        count: 1912,
        nullCount: 0,
        notNullCount: 1912,
        type: 'object',
      },
      structureId: {
        count: 1912,
        nullCount: 0,
        notNullCount: 1912,
        type: 'object',
      },
      dateRupture: {
        count: 1912,
        nullCount: 0,
        notNullCount: 1912,
        type: 'object',
      },
      motifRupture: {
        count: 1912,
        nullCount: 0,
        notNullCount: 1912,
        type: 'string',
      },
    },
  },
  misesEnRelation: {
    count: 935_119,
    fields: {
      _id: {
        count: 935_120,
        nullCount: 0,
        notNullCount: 935_120,
        type: 'object',
      },
      conseiller: {
        count: 935_120,
        nullCount: 0,
        notNullCount: 935_120,
        type: 'object',
      },
      structure: {
        count: 935_120,
        nullCount: 0,
        notNullCount: 935_120,
        type: 'object',
      },
      conseillerCreatedAt: {
        count: 935_098,
        nullCount: 0,
        notNullCount: 935_098,
        type: 'object',
      },
      createdAt: {
        count: 935_119,
        nullCount: 0,
        notNullCount: 935_119,
        type: 'object',
      },
      distance: {
        count: 933_121,
        nullCount: 0,
        notNullCount: 933_121,
        type: 'object',
      },
      statut: {
        count: 935_120,
        nullCount: 0,
        notNullCount: 935_120,
        type: 'string',
      },
      conseillerObj: {
        count: 935_120,
        nullCount: 0,
        notNullCount: 935_120,
        type: 'object',
      },
      structureObj: {
        count: 935_120,
        nullCount: 0,
        notNullCount: 935_120,
        type: 'object',
      },
      dateRecrutement: {
        count: 25_751,
        nullCount: 19_961,
        notNullCount: 5790,
        type: 'object',
      },
      dateDebutDeContrat: {
        count: 5511,
        nullCount: 0,
        notNullCount: 5511,
        type: 'object',
      },
      dateFinDeContrat: {
        count: 4697,
        nullCount: 0,
        notNullCount: 4697,
        type: 'object',
      },
      typeDeContrat: {
        count: 5510,
        nullCount: 0,
        notNullCount: 5510,
        type: 'string',
      },
      reconventionnement: {
        count: 1719,
        nullCount: 0,
        notNullCount: 1719,
        type: 'boolean',
      },
      miseEnRelationReconventionnement: {
        count: 1139,

        nullCount: 0,
        notNullCount: 1139,
        type: 'object',
      },
      dateRupture: {
        count: 2029,
        nullCount: 2,
        notNullCount: 2027,
        type: 'object',
      },
      motifRupture: {
        count: 2031,
        nullCount: 2,
        notNullCount: 2029,
        type: 'string',
      },
      mailCnfsRuptureSentDate: {
        count: 1873,
        nullCount: 0,
        notNullCount: 1873,
        type: 'object',
      },
      resendMailCnfsRupture: {
        count: 1873,
        nullCount: 0,
        notNullCount: 1873,
        type: 'boolean',
      },
      emetteurRupture: {
        count: 1733,
        nullCount: 2,
        notNullCount: 1731,
        type: 'object',
      },
      validateurRupture: {
        count: 1412,
        nullCount: 0,
        notNullCount: 1412,
        type: 'object',
      },
      emetteurRecrutement: {
        count: 769,
        nullCount: 0,
        notNullCount: 769,
        type: 'object',
      },
      salaire: {
        count: 1637,
        nullCount: 0,
        notNullCount: 1637,
        type: 'object',
      },
      phaseConventionnement: {
        count: 1958,
        nullCount: 0,
        notNullCount: 1958,
        type: 'string',
      },
      banniereRefusRecrutement: {
        count: 9,
        nullCount: 0,
        notNullCount: 9,
        type: 'boolean',
      },
      dossierIncompletRupture: {
        count: 149,
        nullCount: 0,
        notNullCount: 149,
        type: 'boolean',
      },
      transfert: { count: 10, nullCount: 0, notNullCount: 10, type: 'object' },
      banniereValidationRenouvellement: {
        count: 1137,

        nullCount: 0,
        notNullCount: 1137,
        type: 'boolean',
      },
      emetteurRenouvellement: {
        count: 1137,
        nullCount: 0,
        notNullCount: 1137,
        type: 'object',
      },
      type: { count: 3556, nullCount: 0, notNullCount: 3556, type: 'string' },
      fusion: { count: 24, nullCount: 0, notNullCount: 24, type: 'object' },
      banniereAjoutRoleCoordinateur: {
        count: 41,
        nullCount: 0,
        notNullCount: 41,
        type: 'boolean',
      },
      miseEnRelationConventionnement: {
        count: 1131,
        nullCount: 0,
        notNullCount: 1131,
        type: 'object',
      },
      contratCoordinateur: {
        count: 35,
        nullCount: 0,
        notNullCount: 35,
        type: 'boolean',
      },
    },
  },
  stats_Territoires: {
    count: 101_965,
    fields: {
      _id: {
        count: 101_965,
        nullCount: 0,
        notNullCount: 101_965,
        type: 'object',
      },
      date: {
        count: 101_965,
        nullCount: 0,
        notNullCount: 101_965,
        type: 'string',
      },
      nombreConseillersCoselec: {
        count: 101_965,
        nullCount: 0,
        notNullCount: 101_965,
        type: 'object',
      },
      cnfsActives: {
        count: 101_965,
        nullCount: 0,
        notNullCount: 101_965,
        type: 'object',
      },
      cnfsInactives: {
        count: 101_965,
        nullCount: 0,
        notNullCount: 101_965,
        type: 'object',
      },
      conseillerIds: {
        count: 101_965,
        nullCount: 0,
        notNullCount: 101_965,
        type: 'object',
      },
      codeDepartement: {
        count: 101_965,
        nullCount: 0,
        notNullCount: 101_965,
        type: 'string',
      },
      codeRegion: {
        count: 101_965,
        nullCount: 0,
        notNullCount: 101_965,
        type: 'string',
      },
      nomDepartement: {
        count: 101_965,
        nullCount: 0,
        notNullCount: 101_965,
        type: 'string',
      },
      nomRegion: {
        count: 101_965,
        nullCount: 0,
        notNullCount: 101_965,
        type: 'string',
      },
      tauxActivation: {
        count: 101_965,
        nullCount: 0,
        notNullCount: 101_965,
        type: 'object',
      },
    },
  },
}

export type ConseillerNumeriqueMongoCollection =
  keyof typeof conseillerNumeriqueMongoCollections
